[package]
name = "fast-writer"
version = "0.3.0"
description = "A Tauri App"
authors = ["Hongli Wen"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "tauri_vite_vue_lib"
crate-type = ["lib", "cdylib", "staticlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [ "protocol-asset", "devtools", "unstable", "tray-icon" ] }
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
anyhow = "1.0.93"
serde_json = "1"
tauri-plugin-clipboard = "2.1.11"
tauri-plugin-log = "2"
tauri-plugin-notification = "2"
log = "0.4.22"
tauri-plugin-store = "2"
xcap = "0.0.14"
png = "0.17.14"
tauri-plugin-http = { version =  "2", features = ["multipart"] }
tauri-plugin-upload = "2"
tokio = "1.41.1"
#image = {version =  "0.25.5", features = ["png"] }
#tauri-plugin-http = "2"
#tauri-plugin-fs = "2"
#tauri-plugin-dialog = "2"

[target.'cfg(target_os = "macos")'.dependencies]
tauri = { version = "2", optional = true, features = ["macos-private-api", "devtools", "unstable"] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-global-shortcut = "2"
tauri-plugin-single-instance = "2"


[profile.dev]
incremental = true # Compile your binary in smaller steps.

[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
lto = "fat" # Enables link-time-optimizations.
opt-level = 3 # Prioritizes small binary size. Use `3` if you prefer speed.
panic = "abort" # Higher performance by disabling panic handlers.
strip = true # Ensures debug symbols are removed.
